# User config
author: "Sarah Nakama"
tagline: ""
description: "student at cv"
# keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "stnakama888@gmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
github: "https://github.com/sarahnak/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

#git ignore
exclude:
- .jekyll-cache