# User config
author: "Sarah Nakama"
tagline: ""
description: "student at cv"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed